{% set name = "nbcx" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d2ecdf7ec47f952c4ae73d74e9c5407a773ba403d83746f9eadeaeb136a834c7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation

requirements:
  host:
    - python >=3.8
    - pip
    - nodejs
    - yarn
    - hatchling >=1.3.1
    - hatch-jupyter-builder
    - jupyterlab >=4,<5
  run:
    - python >=3.8
    - dominate
    - ipywidgets
    - ipython
    - nbformat
    - notebook
    - omegaconf
    - pydantic

test:
  imports:
    - nbcx

about:
  home: http://github.com/timkpaine/nbcx
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A framework for building Jupyter reports with NBConvert
  description: A framework for building Jupyter reports with NBConvert
  dev_url: https://github.com/timkpaine/nbcx

extra:
  recipe-maintainers:
    - timkpaine
