{% set name = "nbcx" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 31009056852c5d2621cfa656f9582cb7ed8dc4855a1e8d68b4b86e16588515af

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - nodejs
    - yarn
    - hatchling >=1.3.1
    - hatch-jupyter-builder
    - jupyterlab >=4,<5
  run:
    - python >={{ python_min }}
    - dominate
    - ipywidgets
    - ipython
    - nbformat
    - notebook
    - omegaconf
    - packaging
    - pydantic

test:
  requires:
    - python {{ python_min }}
  imports:
    - nbcx

about:
  home: http://github.com/timkpaine/nbcx
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A framework for building Jupyter reports with NBConvert
  description: A framework for building Jupyter reports with NBConvert
  dev_url: https://github.com/timkpaine/nbcx

extra:
  recipe-maintainers:
    - timkpaine
